spring:
  application:
    name: zuul
server:  
  port: 8672
  ssl:
    client-auth: want
    enabled: true
    key-store: classpath:zuulkeystore.jks
    key-store-password: zuulpass
    key-alias: zuul

http:
   port: 8673

security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 30000
  sslHostnameValidationEnabled: false
ribbon:
  IsSecured: true
  ConnectTimeout:  10000
  ReadTimeout:  10000
  eureka:
    enabled: true
  TrustStore: classpath:zuulkeystore.jks
  TrustStorePassword : zuulpass
  IsHostnameValidationRequired: false
     