
server:  
  port: 8400
  ssl:
    enabled: true
    key-store: classpath:bitcoinkeystore.ks
    key-store-password: bitcoinpass
    key-alias: bitcoin
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  application:
    name: bitcoin
