
server:  
  port: 8400
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:bitcoinkeystore.ks
    key-store-password: bitcoinpass
    key-alias: bitcoin
    trust-store: classpath:bitcoinkeystore.ks
    trust-store-password: bitcoinpass
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  application:
    name: bitcoin
  datasource:
     username: bitcoindb
     password: bitcoindb
     url: jdbc:mysql://localhost:3306/bitcoin_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  jpa:
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
     generate-ddl: true
     hibernate:
        ddl-auto: create
     show-sql: true
