server:  
  port: 8200
  ssl:
    enabled: true
    key-store: classpath:paypalkeystore.ks
    key-store-password: paypalpass
    key-alias: paypal
security:
  require-ssl: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  application:
    name: paypal
  datasource:
     username: paypaldb
     password: paypaldb
     url: jdbc:mysql://localhost:3306/sellers_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  jpa:
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
     generate-ddl: true
     hibernate:
        ddl-auto: create
     show-sql: true
logging:
  level:
     org: 
        hibernate:
           web: DEBUG
        springframework:
           web: DEBUG   