server:  
  port: 8200
  ssl:
    enabled: true
    key-store: classpath:paypalkeystore.jks
    key-store-password: paypalpass
    key-alias: paypal
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  application:
    name: paypal
