server:  
  port: 8300
  ssl:
    enabled: true
    key-store: classpath:bankkeystore.ks
    key-store-password: bankpass
    key-alias: bank
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  application:
    name: bank
