server:  
  port: 8300
  ssl:
    enabled: true
    key-store: classpath:bankkeystore.ks
    key-store-password: bankpass
    key-alias: bank
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  application:
    name: bank
  datasource:
     username: bankdb
     password: bankdb
     url: jdbc:mysql://localhost:3306/bank_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  jpa:
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
     generate-ddl: true
     hibernate:
        ddl-auto: update
     show-sql: true
logging:
  level:
     org: 
        hibernate:
           web: DEBUG
        springframework:
           web: DEBUG    